server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AuthorizationDB?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: password
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate:
      ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: authentication-authorization-service


eureka:
  client:
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}

jwt:
  secret: mySecret

feign:
  client:
    config:
      account:
        connectTimeout: 60000
        readTimeout: 60000



